// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSnnT96Rh7QhikqZvqOwpzC1lvxR3e8CY',
    appId: '1:961609328461:web:99c0cadc25d2dee785f904',
    messagingSenderId: '961609328461',
    projectId: 'desicionmakerapp',
    authDomain: 'desicionmakerapp.firebaseapp.com',
    storageBucket: 'desicionmakerapp.appspot.com',
    measurementId: 'G-TVWEZYNX4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj8RfOyhj4xn5vQ4hax90f6EaVPwQjtis',
    appId: '1:961609328461:android:2052dc1d073155e985f904',
    messagingSenderId: '961609328461',
    projectId: 'desicionmakerapp',
    storageBucket: 'desicionmakerapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbNsZzT96auwM5AIw2YW0a7nGVCqo4Ot4',
    appId: '1:961609328461:ios:4acb0e7ad6324b9385f904',
    messagingSenderId: '961609328461',
    projectId: 'desicionmakerapp',
    storageBucket: 'desicionmakerapp.appspot.com',
    iosClientId: '961609328461-rfsf6cr4fmgtlkkesh6gc4u74f6f4bng.apps.googleusercontent.com',
    iosBundleId: 'com.example.desicionMakerApp',
  );
}
